// resources/js/components/AppearanceTabs.vue
<script setup lang="ts">
import { useAppearance } from '@/composables/useAppearance'
import { Monitor, Moon, Sun } from 'lucide-vue-next'

interface Props {
  class?: string
}

const { class: containerClass = '' } = defineProps<Props>()

const { appearance, updateAppearance } = useAppearance()

const tabs = [
  { value: 'light', Icon: Sun, label: 'Light' },
  { value: 'dark', Icon: Moon, label: 'Dark' },
  { value: 'system', Icon: Monitor, label: 'System' },
] as const
</script>

<template>
  <div class="inline-flex gap-1 rounded-lg bg-neutral-100 p-1 dark:bg-neutral-800" :class="[containerClass]">
    <button
      v-for="{ value, Icon, label } in tabs"
      :key="value"
      class="flex items-center rounded-md px-3.5 py-1.5 transition-colors" :class="[
        appearance === value
          ? 'bg-white shadow-sm dark:bg-neutral-700 dark:text-neutral-100'
          : 'text-neutral-500 hover:bg-neutral-200/60 hover:text-black dark:text-neutral-400 dark:hover:bg-neutral-700/60',
      ]"
      @click="updateAppearance(value)"
    >
      <component :is="Icon" class="-ml-1 h-4 w-4" />
      <span class="ml-1.5 text-sm">{{ label }}</span>
    </button>
  </div>
</template>

// resources/js/components/appearance-tabs.tsx
import type { Appearance } from '@/hooks/use-appearance'
import type { LucideIcon } from 'lucide-react'
import type { HTMLAttributes } from 'react'
import { useAppearance } from '@/hooks/use-appearance'
import { cn } from '@/lib/utils'
import { Monitor, Moon, Sun } from 'lucide-react'

export default function AppearanceToggleTab({ className = '', ...props }: HTMLAttributes<HTMLDivElement>) {
  const { appearance, updateAppearance } = useAppearance()

  const tabs: { value: Appearance, icon: LucideIcon, label: string }[] = [
    { value: 'light', icon: Sun, label: 'Light' },
    { value: 'dark', icon: Moon, label: 'Dark' },
    { value: 'system', icon: Monitor, label: 'System' },
  ]

  return (
    <div className={cn('inline-flex gap-1 rounded-lg bg-neutral-100 p-1 dark:bg-neutral-800', className)} {...props}>
      {tabs.map(({ value, icon: Icon, label }) => (
        <button
          type="button"
          key={value}
          onClick={() => updateAppearance(value)}
          className={cn(
            'flex items-center rounded-md px-3.5 py-1.5 transition-colors',
            appearance === value
              ? 'bg-white shadow-xs dark:bg-neutral-700 dark:text-neutral-100'
              : 'text-neutral-500 hover:bg-neutral-200/60 hover:text-black dark:text-neutral-400 dark:hover:bg-neutral-700/60',
          )}
        >
          <Icon className="-ml-1 h-4 w-4" />
          <span className="ml-1.5 text-sm">{label}</span>
        </button>
      ))}
    </div>
  )
}
