// resources/js/components/Heading.vue
<script setup lang="ts">
import { Separator } from '@/components/ui/separator'

interface Props {
  title: string
  description?: string
}

defineProps<Props>()
</script>

<template>
  <div class="mb-8 space-y-0.5">
    <h2 class="text-xl font-semibold tracking-tight">
      {{ title }}
    </h2>
    <p v-if="description" class="text-sm text-muted-foreground">
      {{ description }}
    </p>
  </div>
  <Separator class="my-6" />
</template>

// resources/js/components/heading.tsx
export default function Heading({ title, description }: { title: string, description?: string }) {
  return (
    <div className="mb-8 space-y-0.5">
      <h2 className="text-xl font-semibold tracking-tight">{title}</h2>
      {description && <p className="text-muted-foreground text-sm">{description}</p>}
    </div>
  )
}
