// resources/js/components/TextLink.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3'

interface Props {
  href: string
  tabindex?: number
  method?: string
  as?: string
}

defineProps<Props>()
</script>

<template>
  <Link
    :href="href"
    :tabindex="tabindex"
    :method="method"
    :as="as"
    class="hover:!decoration-current text-foreground underline decoration-neutral-300 underline-offset-4 transition-colors duration-300 ease-out dark:decoration-neutral-500"
  >
    <slot />
  </Link>
</template>

// resources/js/components/text-link.tsx
import type { ComponentProps } from 'react'
import { cn } from '@/lib/utils'
import { Link } from '@inertiajs/react'

type LinkProps = ComponentProps<typeof Link>

export default function TextLink({ className = '', children, ...props }: LinkProps) {
  return (
    <Link
      className={cn(
        'text-foreground underline decoration-neutral-300 underline-offset-4 transition-colors duration-300 ease-out hover:decoration-current! dark:decoration-neutral-500',
        className,
      )}
      {...props}
    >
      {children}
    </Link>
  )
}
