// resources/js/layouts/auth/AuthCardLayout.vue
<script setup lang="ts">
import AppLogoIcon from '@/components/AppLogoIcon.vue'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Link } from '@inertiajs/vue3'

defineProps<{
  title?: string
  description?: string
}>()
</script>

<template>
  <div class="flex min-h-svh flex-col items-center justify-center gap-6 bg-muted p-6 md:p-10">
    <div class="flex w-full max-w-md flex-col gap-6">
      <Link :href="route('home')" class="flex items-center gap-2 self-center font-medium">
        <div class="flex h-9 w-9 items-center justify-center">
          <AppLogoIcon class="size-9 fill-current text-black dark:text-white" />
        </div>
      </Link>

      <div class="flex flex-col gap-6">
        <Card class="rounded-xl">
          <CardHeader class="px-10 pb-0 pt-8 text-center">
            <CardTitle class="text-xl">
              {{ title }}
            </CardTitle>
            <CardDescription>
              {{ description }}
            </CardDescription>
          </CardHeader>
          <CardContent class="px-10 py-8">
            <slot />
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>

// resources/js/layouts/auth/auth-card-layout.tsx
import type { PropsWithChildren } from 'react'
import AppLogoIcon from '@/components/app-logo-icon'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Link } from '@inertiajs/react'

export default function AuthCardLayout({
  children,
  title,
  description,
}: PropsWithChildren<{
  name?: string
  title?: string
  description?: string
}>) {
  return (
    <div className="bg-muted flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
      <div className="flex w-full max-w-md flex-col gap-6">
        <Link href={route('home')} className="flex items-center gap-2 self-center font-medium">
          <div className="flex h-9 w-9 items-center justify-center">
            <AppLogoIcon className="size-9 fill-current text-black dark:text-white" />
          </div>
        </Link>

        <div className="flex flex-col gap-6">
          <Card className="rounded-xl">
            <CardHeader className="px-10 pt-8 pb-0 text-center">
              <CardTitle className="text-xl">{title}</CardTitle>
              <CardDescription>{description}</CardDescription>
            </CardHeader>
            <CardContent className="px-10 py-8">{children}</CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
