// resources/js/layouts/auth/auth-split-layout.tsx
import type { SharedData } from '@/types'
import type { PropsWithChildren } from 'react'
import AppLogoIcon from '@/components/app-logo-icon'
import { Link, usePage } from '@inertiajs/react'

interface AuthLayoutProps {
  title?: string
  description?: string
}

export default function AuthSplitLayout({ children, title, description }: PropsWithChildren<AuthLayoutProps>) {
  const { name, quote } = usePage<SharedData>().props

  return (
    <div className="relative grid h-dvh flex-col items-center justify-center px-8 sm:px-0 lg:max-w-none lg:grid-cols-2 lg:px-0">
      <div className="bg-muted relative hidden h-full flex-col p-10 text-white lg:flex dark:border-r">
        <div className="absolute inset-0 bg-zinc-900" />
        <Link href={route('home')} className="relative z-20 flex items-center text-lg font-medium">
          <AppLogoIcon className="mr-2 size-8 fill-current text-white" />
          {name}
        </Link>
        {quote && (
          <div className="relative z-20 mt-auto">
            <blockquote className="space-y-2">
              <p className="text-lg">
                &ldquo;
                {quote.message}
                &rdquo;
              </p>
              <footer className="text-sm text-neutral-300">{quote.author}</footer>
            </blockquote>
          </div>
        )}
      </div>
      <div className="w-full lg:p-8">
        <div className="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
          <Link href={route('home')} className="relative z-20 flex items-center justify-center lg:hidden">
            <AppLogoIcon className="h-10 fill-current text-black sm:h-12" />
          </Link>
          <div className="flex flex-col items-start gap-2 text-left sm:items-center sm:text-center">
            <h1 className="text-xl font-medium">{title}</h1>
            <p className="text-muted-foreground text-sm text-balance">{description}</p>
          </div>
          {children}
        </div>
      </div>
    </div>
  )
}

// resources/js/layouts/auth/AuthSplitLayout.vue
<script setup lang="ts">
import AppLogoIcon from '@/components/AppLogoIcon.vue'
import { Link, usePage } from '@inertiajs/vue3'

defineProps<{
  title?: string
  description?: string
}>()
const page = usePage()
const name = page.props.name
const quote = page.props.quote
</script>

<template>
  <div class="relative grid h-dvh flex-col items-center justify-center px-8 sm:px-0 lg:max-w-none lg:grid-cols-2 lg:px-0">
    <div class="relative hidden h-full flex-col bg-muted p-10 text-white dark:border-r lg:flex">
      <div class="absolute inset-0 bg-zinc-900" />
      <Link :href="route('home')" class="relative z-20 flex items-center text-lg font-medium">
        <AppLogoIcon class="mr-2 size-8 fill-current text-white" />
        {{ name }}
      </Link>
      <div v-if="quote" class="relative z-20 mt-auto">
        <blockquote class="space-y-2">
          <p class="text-lg">
            &ldquo;{{ quote.message }}&rdquo;
          </p>
          <footer class="text-sm text-neutral-300">
            {{ quote.author }}
          </footer>
        </blockquote>
      </div>
    </div>
    <div class="lg:p-8">
      <div class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
        <div class="flex flex-col space-y-2 text-center">
          <h1 v-if="title" class="text-xl font-medium tracking-tight">
            {{ title }}
          </h1>
          <p v-if="description" class="text-sm text-muted-foreground">
            {{ description }}
          </p>
        </div>
        <slot />
      </div>
    </div>
  </div>
</template>
