// resources/js/pages/settings/Appearance.vue
<script setup lang="ts">
import type { BreadcrumbItem } from '@/types'

import AppearanceTabs from '@/components/AppearanceTabs.vue'
import HeadingSmall from '@/components/HeadingSmall.vue'
import AppLayout from '@/layouts/AppLayout.vue'

import SettingsLayout from '@/layouts/settings/Layout.vue'
import { Head } from '@inertiajs/vue3'

const breadcrumbItems: BreadcrumbItem[] = [
  {
    title: 'Appearance settings',
    href: '/settings/appearance',
  },
]
</script>

<template>
  <AppLayout :breadcrumbs="breadcrumbItems">
    <Head title="Appearance settings" />

    <SettingsLayout>
      <div class="space-y-6">
        <HeadingSmall title="Appearance settings" description="Update your account's appearance settings" />
        <AppearanceTabs />
      </div>
    </SettingsLayout>
  </AppLayout>
</template>

// resources/js/pages/settings/appearance.tsx
import type { BreadcrumbItem } from '@/types'

import AppearanceTabs from '@/components/appearance-tabs'
import HeadingSmall from '@/components/heading-small'
import AppLayout from '@/layouts/app-layout'

import SettingsLayout from '@/layouts/settings/layout'
import { Head } from '@inertiajs/react'

const breadcrumbs: BreadcrumbItem[] = [
  {
    title: 'Appearance settings',
    href: '/settings/appearance',
  },
]

export default function Appearance() {
  return (
    <AppLayout breadcrumbs={breadcrumbs}>
      <Head title="Appearance settings" />

      <SettingsLayout>
        <div className="space-y-6">
          <HeadingSmall title="Appearance settings" description="Update your account's appearance settings" />
          <AppearanceTabs />
        </div>
      </SettingsLayout>
    </AppLayout>
  )
}
