// resources/js/pages/auth/confirm-password.tsx
import type { FormEventHandler } from 'react'
import InputError from '@/components/input-error'
import { Button } from '@/components/ui/button'

import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import AuthLayout from '@/layouts/auth-layout'
// Components
import { Head, useForm } from '@inertiajs/react'
import { LoaderCircle } from 'lucide-react'

export default function ConfirmPassword() {
  const { data, setData, post, processing, errors, reset } = useForm({
    password: '',
  })

  const submit: FormEventHandler = (e) => {
    e.preventDefault()

    post(route('password.confirm'), {
      onFinish: () => reset('password'),
    })
  }

  return (
    <AuthLayout
      title="Confirm your password"
      description="This is a secure area of the application. Please confirm your password before continuing."
    >
      <Head title="Confirm password" />

      <form onSubmit={submit}>
        <div className="space-y-6">
          <div className="grid gap-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              name="password"
              placeholder="Password"
              autoComplete="current-password"
              value={data.password}
              autoFocus
              onChange={e => setData('password', e.target.value)}
            />

            <InputError message={errors.password} />
          </div>

          <div className="flex items-center">
            <Button className="w-full" disabled={processing}>
              {processing && <LoaderCircle className="h-4 w-4 animate-spin" />}
              Confirm password
            </Button>
          </div>
        </div>
      </form>
    </AuthLayout>
  )
}

// resources/js/pages/auth/ConfirmPassword.vue
<script setup lang="ts">
import InputError from '@/components/InputError.vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import AuthLayout from '@/layouts/AuthLayout.vue'
import { Head, useForm } from '@inertiajs/vue3'
import { LoaderCircle } from 'lucide-vue-next'

const form = useForm({
  password: '',
})

function submit() {
  form.post(route('password.confirm'), {
    onFinish: () => {
      form.reset()
    },
  })
}
</script>

<template>
  <AuthLayout title="Confirm your password" description="This is a secure area of the application. Please confirm your password before continuing.">
    <Head title="Confirm password" />

    <form @submit.prevent="submit">
      <div class="space-y-6">
        <div class="grid gap-2">
          <Label html-for="password">Password</Label>
          <Input
            id="password"
            v-model="form.password"
            type="password"
            class="mt-1 block w-full"
            required
            autocomplete="current-password"
            autofocus
          />

          <InputError :message="form.errors.password" />
        </div>

        <div class="flex items-center">
          <Button class="w-full" :disabled="form.processing">
            <LoaderCircle v-if="form.processing" class="h-4 w-4 animate-spin" />
            Confirm Password
          </Button>
        </div>
      </div>
    </form>
  </AuthLayout>
</template>
