// resources/js/pages/auth/verify-email.tsx
import type { FormEventHandler } from 'react'
import TextLink from '@/components/text-link'
import { Button } from '@/components/ui/button'

import AuthLayout from '@/layouts/auth-layout'
// Components
import { Head, useForm } from '@inertiajs/react'
import { LoaderCircle } from 'lucide-react'

export default function VerifyEmail({ status }: { status?: string }) {
  const { post, processing } = useForm({})

  const submit: FormEventHandler = (e) => {
    e.preventDefault()

    post(route('verification.send'))
  }

  return (
    <AuthLayout title="Verify email" description="Please verify your email address by clicking on the link we just emailed to you.">
      <Head title="Email verification" />

      {status === 'verification-link-sent' && (
        <div className="mb-4 text-center text-sm font-medium text-green-600">
          A new verification link has been sent to the email address you provided during registration.
        </div>
      )}

      <form onSubmit={submit} className="space-y-6 text-center">
        <Button disabled={processing} variant="secondary">
          {processing && <LoaderCircle className="h-4 w-4 animate-spin" />}
          Resend verification email
        </Button>

        <TextLink href={route('logout')} method="post" className="mx-auto block text-sm">
          Log out
        </TextLink>
      </form>
    </AuthLayout>
  )
}

// resources/js/pages/auth/VerifyEmail.vue
<script setup lang="ts">
import TextLink from '@/components/TextLink.vue'
import { Button } from '@/components/ui/button'
import AuthLayout from '@/layouts/AuthLayout.vue'
import { Head, useForm } from '@inertiajs/vue3'
import { LoaderCircle } from 'lucide-vue-next'

defineProps<{
  status?: string
}>()

const form = useForm({})

function submit() {
  form.post(route('verification.send'))
}
</script>

<template>
  <AuthLayout title="Verify email" description="Please verify your email address by clicking on the link we just emailed to you.">
    <Head title="Email verification" />

    <div v-if="status === 'verification-link-sent'" class="mb-4 text-center text-sm font-medium text-green-600">
      A new verification link has been sent to the email address you provided during registration.
    </div>

    <form class="space-y-6 text-center" @submit.prevent="submit">
      <Button :disabled="form.processing" variant="secondary">
        <LoaderCircle v-if="form.processing" class="h-4 w-4 animate-spin" />
        Resend verification email
      </Button>

      <TextLink :href="route('logout')" method="post" as="button" class="mx-auto block text-sm">
        Log out
      </TextLink>
    </form>
  </AuthLayout>
</template>
